/**
 * The competitive meta, as published at https://play.limitlesstcg.com/decks.
 *
 * A deck's identity is the Pokemon it is named for, stored as sprite ids so
 * the archetype string renders directly. Entries whose name carries no Pokemon
 * -- "Festival Lead", "Basic Box", "Tera Box" -- are omitted: they cannot be
 * matched from a log and cannot be drawn.
 *
 * `share` is the deck's meta share at capture time, used only to break ties
 * between decks that match a log equally well. Refresh by re-reading the
 * Limitless page; nothing here is fetched at runtime, so importing a log never
 * depends on Limitless being reachable.
 *
 * Captured 2026-08-17.
 */
export interface MetaDeck {
  /** Sprite ids, in the order the deck is normally named. */
  pokemon: string[];
  /** Percentage of the meta at capture time. */
  share: number;
  /** The Limitless deck name, kept so a row can be traced back to its source. */
  deck: string;
}

export const META_DECKS: MetaDeck[] = [
  { pokemon: ['excadrill'], share: 7.79, deck: "Mega Excadrill" },
  { pokemon: ['dragapult'], share: 6.96, deck: "Dragapult" },
  { pokemon: ['dragapult', 'blaziken'], share: 5.99, deck: "Dragapult Blaziken" },
  { pokemon: ['dragapult', 'dusknoir'], share: 5.39, deck: "Dragapult Dusknoir" },
  { pokemon: ['slowking'], share: 5.26, deck: "Slowking" },
  { pokemon: ['alakazam', 'dudunsparce'], share: 5.16, deck: "Alakazam Dudunsparce" },
  { pokemon: ['zoroark'], share: 5.16, deck: "N's Zoroark" },
  { pokemon: ['grimmsnarl', 'froslass'], share: 4.67, deck: "Grimmsnarl Froslass" },
  { pokemon: ['dhelmise'], share: 4.1, deck: "Dhelmise" },
  { pokemon: ['toucannon'], share: 3.39, deck: "Toucannon" },
  { pokemon: ['raging-bolt', 'ogerpon'], share: 1.79, deck: "Raging Bolt Ogerpon" },
  { pokemon: ['lucario'], share: 1.77, deck: "Mega Lucario" },
  { pokemon: ['greninja'], share: 1.7, deck: "Mega Greninja" },
  { pokemon: ['lucario', 'hariyama'], share: 1.61, deck: "Lucario Hariyama" },
  { pokemon: ['ogerpon', 'meganium', 'hydrapple'], share: 1.41, deck: "Ogerpon Meganium Hydrapple" },
  { pokemon: ['honchkrow'], share: 1.39, deck: "Rocket's Honchkrow" },
  { pokemon: ['absol'], share: 1.24, deck: "Mega Absol Box" },
  { pokemon: ['chandelure'], share: 1.23, deck: "Mega Chandelure" },
  { pokemon: ['beedrill'], share: 1.22, deck: "Beedrill" },
  { pokemon: ['garchomp'], share: 1.18, deck: "Cynthia's Garchomp" },
  { pokemon: ['kangaskhan', 'bouffalant'], share: 0.85, deck: "Kangaskhan Bouffalant" },
  { pokemon: ['manectric', 'eelektrik'], share: 0.79, deck: "Manectric Eelektrik" },
  { pokemon: ['mewtwo'], share: 0.73, deck: "Rocket's Mewtwo" },
  { pokemon: ['typhlosion'], share: 0.73, deck: "Ethan's Typhlosion" },
  { pokemon: ['crustle'], share: 0.72, deck: "Crustle" },
  { pokemon: ['toxtricity'], share: 0.69, deck: "Toxtricity Box" },
  { pokemon: ['trevenant'], share: 0.68, deck: "Hop's Trevenant" },
  { pokemon: ['ceruledge'], share: 0.68, deck: "Ceruledge" },
  { pokemon: ['greninja'], share: 0.67, deck: "Greninja" },
  { pokemon: ['starmie', 'froslass'], share: 0.65, deck: "Starmie Froslass" },
  { pokemon: ['venusaur'], share: 0.65, deck: "Mega Venusaur" },
  { pokemon: ['darkrai'], share: 0.53, deck: "Mega Darkrai" },
  { pokemon: ['starmie'], share: 0.48, deck: "Mega Starmie" },
  { pokemon: ['lopunny', 'dudunsparce'], share: 0.45, deck: "Lopunny Dudunsparce" },
  { pokemon: ['dragapult', 'dudunsparce'], share: 0.44, deck: "Dragapult Dudunsparce" },
  { pokemon: ['cinccino'], share: 0.43, deck: "Cinccino" },
  { pokemon: ['starmie', 'dusknoir'], share: 0.39, deck: "Starmie Dusknoir" },
  { pokemon: ['blaziken', 'zoroark'], share: 0.39, deck: "Blaziken Zoroark" },
  { pokemon: ['toxtricity'], share: 0.36, deck: "Toxtricity" },
  { pokemon: ['metagross'], share: 0.31, deck: "Steven's Metagross" },
  { pokemon: ['froslass', 'munkidori'], share: 0.31, deck: "Froslass Munkidori" },
  { pokemon: ['ogerpon', 'meganium', 'arboliva'], share: 0.29, deck: "Ogerpon Meganium Arboliva" },
  { pokemon: ['wailord'], share: 0.29, deck: "Wailord" },
  { pokemon: ['abomasnow'], share: 0.26, deck: "Mega Abomasnow" },
  { pokemon: ['clefairy'], share: 0.25, deck: "Lillie's Clefairy" },
  { pokemon: ['clefairy', 'ogerpon'], share: 0.25, deck: "Clefairy Ogerpon" },
  { pokemon: ['metagross'], share: 0.23, deck: "Metagross" },
  { pokemon: ['okidogi', 'barbaracle'], share: 0.22, deck: "Okidogi Barbaracle" },
  { pokemon: ['froslass'], share: 0.22, deck: "Mega Froslass" },
  { pokemon: ['lopunny', 'dusknoir'], share: 0.22, deck: "Lopunny Dusknoir" },
  { pokemon: ['dragonite'], share: 0.22, deck: "Mega Dragonite" },
  { pokemon: ['flareon', 'noctowl'], share: 0.21, deck: "Flareon Noctowl" },
  { pokemon: ['doublade'], share: 0.21, deck: "Doublade" },
  { pokemon: ['victreebel'], share: 0.2, deck: "Erika's Victreebel" },
  { pokemon: ['iron-thorns'], share: 0.2, deck: "Iron Thorns" },
  { pokemon: ['zygarde', 'barbaracle'], share: 0.19, deck: "Zygarde Barbaracle" },
  { pokemon: ['diancie', 'dusknoir'], share: 0.19, deck: "Diancie Dusknoir" },
  { pokemon: ['grimmsnarl'], share: 0.19, deck: "Marnie's Grimmsnarl" },
  { pokemon: ['charizard'], share: 0.19, deck: "Mega Charizard X" },
  { pokemon: ['sharpedo', 'toxtricity'], share: 0.18, deck: "Sharpedo Toxtricity" },
  { pokemon: ['froslass', 'dudunsparce'], share: 0.17, deck: "Froslass Dudunsparce" },
  { pokemon: ['bellibolt'], share: 0.15, deck: "Iono's Bellibolt" },
  { pokemon: ['archaludon'], share: 0.14, deck: "Archaludon" },
  { pokemon: ['ogerpon', 'meganium'], share: 0.14, deck: "Ogerpon Meganium" },
  { pokemon: ['hydreigon'], share: 0.14, deck: "Hydreigon" },
  { pokemon: ['feraligatr'], share: 0.14, deck: "Mega Feraligatr" },
  { pokemon: ['zacian'], share: 0.13, deck: "Hop's Zacian" },
  { pokemon: ['palafin'], share: 0.11, deck: "Palafin" },
  { pokemon: ['yanmega'], share: 0.1, deck: "Yanmega" },
  { pokemon: ['ursaluna', 'lunatone'], share: 0.1, deck: "Ursaluna Lunatone" },
  { pokemon: ['decidueye'], share: 0.09, deck: "Decidueye" },
  { pokemon: ['bronzong'], share: 0.09, deck: "Bronzong" },
  { pokemon: ['nidoking'], share: 0.09, deck: "Rocket's Nidoking" },
  { pokemon: ['wailord'], share: 0.08, deck: "Wailord" },
  { pokemon: ['archaludon', 'zoroark'], share: 0.07, deck: "Archaludon Zoroark" },
  { pokemon: ['blissey'], share: 0.06, deck: "Blissey" },
  { pokemon: ['dragapult', 'froslass'], share: 0.06, deck: "Dragapult Froslass" },
  { pokemon: ['camerupt'], share: 0.06, deck: "Mega Camerupt" },
  { pokemon: ['blaziken'], share: 0.06, deck: "Blaziken" },
  { pokemon: ['gengar'], share: 0.06, deck: "Gengar" },
  { pokemon: ['jellicent', 'dusknoir'], share: 0.06, deck: "Jellicent Dusknoir" },
  { pokemon: ['archaludon', 'dudunsparce'], share: 0.06, deck: "Archaludon Dudunsparce" },
  { pokemon: ['greninja', 'blaziken'], share: 0.05, deck: "Greninja Blaziken" },
  { pokemon: ['tauros-paldea-blaze'], share: 0.05, deck: "Paldean Tauros" },
  { pokemon: ['joltik'], share: 0.05, deck: "Joltik Box" },
  { pokemon: ['eelektrik'], share: 0.05, deck: "Eelektrik" },
  { pokemon: ['gyarados'], share: 0.05, deck: "Misty's Gyarados" },
  { pokemon: ['azumarill'], share: 0.05, deck: "Azumarill" },
  { pokemon: ['spidops'], share: 0.05, deck: "Rocket's Spidops" },
  { pokemon: ['feraligatr'], share: 0.04, deck: "Feraligatr" },
  { pokemon: ['dudunsparce'], share: 0.04, deck: "Dudunsparce Control" },
  { pokemon: ['terapagos', 'noctowl'], share: 0.04, deck: "Terapagos Noctowl" },
  { pokemon: ['zygarde'], share: 0.04, deck: "Mega Zygarde" },
  { pokemon: ['lopunny'], share: 0.04, deck: "Mega Lopunny" },
  { pokemon: ['magcargo'], share: 0.04, deck: "Ethan's Magcargo" },
  { pokemon: ['sinistcha', 'ogerpon'], share: 0.03, deck: "Sinistcha Ogerpon" },
  { pokemon: ['scizor'], share: 0.03, deck: "Scizor" },
  { pokemon: ['flygon'], share: 0.03, deck: "Flygon" },
  { pokemon: ['sylveon'], share: 0.03, deck: "Sylveon" },
  { pokemon: ['gengar'], share: 0.03, deck: "Mega Gengar" },
  { pokemon: ['raging-bolt', 'bellibolt'], share: 0.02, deck: "Raging Bolt Bellibolt" },
  { pokemon: ['alakazam'], share: 0.02, deck: "Alakazam" },
  { pokemon: ['scovillain'], share: 0.02, deck: "Scovillain" },
  { pokemon: ['sharpedo'], share: 0.02, deck: "Mega Sharpedo" },
  { pokemon: ['dragonite', 'eelektrik'], share: 0.02, deck: "Dragonite Eelektrik" },
  { pokemon: ['zoroark', 'crustle'], share: 0.02, deck: "Zoroark Crustle" },
  { pokemon: ['manectric'], share: 0.02, deck: "Mega Manectric" },
  { pokemon: ['luxray'], share: 0.02, deck: "Luxray" },
  { pokemon: ['mamoswine'], share: 0.02, deck: "Mamoswine" },
  { pokemon: ['seaking'], share: 0.01, deck: "Seaking Festival Lead" },
  { pokemon: ['flareon'], share: 0.01, deck: "Flareon" },
  { pokemon: ['latias'], share: 0.01, deck: "Mega Latias" },
  { pokemon: ['ogerpon-cornerstone'], share: 0.01, deck: "Cornerstone Mask Ogerpon" },
  { pokemon: ['cinderace'], share: 0.01, deck: "Cinderace" },
  { pokemon: ['diancie'], share: 0.01, deck: "Mega Diancie" },
  { pokemon: ['dragapult', 'zoroark'], share: 0.01, deck: "Dragapult Zoroark" },
  { pokemon: ['tyranitar'], share: 0.01, deck: "Tyranitar" },
  { pokemon: ['hydrapple'], share: 0.01, deck: "Hydrapple" },
  { pokemon: ['slaking'], share: 0.01, deck: "Slaking" },
  { pokemon: ['raging-bolt'], share: 0.01, deck: "Raging Bolt" },
  { pokemon: ['hydrapple', 'ogerpon'], share: 0.0, deck: "Hydrapple Ogerpon" },
  { pokemon: ['porygon-z'], share: 0.0, deck: "Rocket's Porygon-Z" },
  { pokemon: ['brute-bonnet', 'toxtricity'], share: 0.0, deck: "Toxtricity Brute Bonnet" },
  { pokemon: ['exeggutor-alola'], share: 0.0, deck: "Alolan Exeggutor" },
  { pokemon: ['milotic'], share: 0.0, deck: "Milotic" },
  { pokemon: ['okidogi'], share: 0.0, deck: "Okidogi" },
  { pokemon: ['incineroar'], share: 0.0, deck: "Incineroar" },
  { pokemon: ['ursaluna-bloodmoon'], share: 0.0, deck: "Bloodmoon Ursaluna" },
  { pokemon: ['heatran', 'metang'], share: 0.0, deck: "Heatran Metang" },
];

/**
 * Consistency and utility Pokemon that get played across many decks without
 * ever being the deck's identity. Dudunsparce is the case that forces this to
 * exist: it appears more often than Beedrill in a Beedrill list, so ranking on
 * how much a Pokemon is played would name the wrong deck.
 *
 * This never blocks a listed archetype -- "Alakazam Dudunsparce" still matches
 * on its own terms. It only stops a staple from being mistaken for an identity
 * when no listed deck fits.
 */
export const TECH_POKEMON = new Set([
  'dudunsparce',
  'budew',
  'fezandipiti',
  'munkidori',
  'rotom',
  'lumineon',
  'squawkabilly',
  'jirachi',
  'manaphy',
  'pidgeot',
]);

/**
 * Pre-evolutions mapped to the Pokemon their deck is named for. A log shows
 * what was played, which is often only the basic: a Beedrill list shows Weedle
 * and may never show Beedrill at all.
 *
 * Eevee is deliberately absent -- it evolves into several decks' worth of
 * Pokemon, so it identifies nothing. Metang is absent because "Heatran Metang"
 * names it in its own right.
 */
export const EVOLVES_INTO: Record<string, string> = {
  abra: 'alakazam', kadabra: 'alakazam',
  applin: 'hydrapple', dipplin: 'hydrapple',
  azurill: 'azumarill', marill: 'azumarill',
  beldum: 'metagross',
  bellsprout: 'victreebel', weepinbell: 'victreebel',
  binacle: 'barbaracle',
  bronzor: 'bronzong',
  buneary: 'lopunny',
  bulbasaur: 'venusaur', ivysaur: 'venusaur',
  capsakid: 'scovillain',
  carvanha: 'sharpedo',
  charcadet: 'ceruledge',
  charmander: 'charizard', charmeleon: 'charizard',
  chikorita: 'meganium', bayleef: 'meganium',
  cleffa: 'clefairy',
  cyndaquil: 'typhlosion', quilava: 'typhlosion',
  deino: 'hydreigon', zweilous: 'hydreigon',
  dratini: 'dragonite', dragonair: 'dragonite',
  dreepy: 'dragapult', drakloak: 'dragapult',
  drilbur: 'excadrill',
  dunsparce: 'dudunsparce',
  duraludon: 'archaludon',
  duskull: 'dusknoir', dusclops: 'dusknoir',
  dwebble: 'crustle',
  electrike: 'manectric',
  feebas: 'milotic',
  finizen: 'palafin',
  frillish: 'jellicent',
  froakie: 'greninja', frogadier: 'greninja',
  gastly: 'gengar', haunter: 'gengar',
  gible: 'garchomp', gabite: 'garchomp',
  goldeen: 'seaking',
  happiny: 'blissey', chansey: 'blissey',
  honedge: 'doublade',
  hoothoot: 'noctowl',
  impidimp: 'grimmsnarl', morgrem: 'grimmsnarl',
  kakuna: 'beedrill', weedle: 'beedrill',
  lampent: 'chandelure', litwick: 'chandelure',
  larvitar: 'tyranitar', pupitar: 'tyranitar',
  litten: 'incineroar', torracat: 'incineroar',
  magikarp: 'gyarados',
  makuhita: 'hariyama',
  minccino: 'cinccino',
  murkrow: 'honchkrow',
  nidorino: 'nidoking',
  numel: 'camerupt',
  phantump: 'trevenant',
  pikipek: 'toucannon', trumbeak: 'toucannon',
  piloswine: 'mamoswine', swinub: 'mamoswine',
  poltchageist: 'sinistcha',
  porygon: 'porygon-z', porygon2: 'porygon-z',
  riolu: 'lucario',
  rowlet: 'decidueye', dartrix: 'decidueye',
  scorbunny: 'cinderace', raboot: 'cinderace',
  scyther: 'scizor',
  shinx: 'luxray', luxio: 'luxray',
  slakoth: 'slaking', vigoroth: 'slaking',
  slowpoke: 'slowking',
  slugma: 'magcargo',
  smoliv: 'arboliva', dolliv: 'arboliva',
  snorunt: 'froslass',
  snover: 'abomasnow',
  staryu: 'starmie',
  tadbulb: 'bellibolt',
  tarountula: 'spidops',
  teddiursa: 'ursaluna',
  torchic: 'blaziken', combusken: 'blaziken',
  totodile: 'feraligatr', croconaw: 'feraligatr',
  toxel: 'toxtricity',
  trapinch: 'flygon', vibrava: 'flygon',
  tynamo: 'eelektrik',
  wailmer: 'wailord',
  yanma: 'yanmega',
  zorua: 'zoroark',
};
